#!/usr/bin/env python3
from pathlib import Path

i386_darwin = Path("src/gcc/config/i386/darwin.h")
text = i386_darwin.read_text()
text = text.replace(
    '#define CC1_SPEC "%(cc1_cpu) \\\n'
    '  %{!mkernel:%{!static:%{!mdynamic-no-pic:-fPIC}}} \\\n'
    '  %{!mmacosx-version-min=*:-mmacosx-version-min=%(darwin_minversion)} \\\n',
    '#define CC1_SPEC " \\\n'
    '  %{!mkernel:%{!static:%{!mdynamic-no-pic:-fPIC}}} \\\n',
)
i386_darwin.write_text(text)

darwin_driver = Path("src/gcc/config/darwin-driver.c")
text = darwin_driver.read_text()
text = text.replace(
    '    /* The bootstrap compiler is built on modern Darwin hosts but targets the\n'
    '       old x86_64 Darwin ABI used by the bootstrap chain.  GCC 4.6 cannot parse\n'
    '       host releases such as macOS 14+ as -mmacosx-version-min values, so keep\n'
    '       the native driver deterministic unless the caller set MACOSX_DEPLOYMENT_TARGET\n'
    '       to an old 10.x deployment explicitly.  */\n'
    '    ++*decoded_options_count;\n'
    '    *decoded_options = XNEWVEC (struct cl_decoded_option,\n'
    '\t\t\t\t*decoded_options_count);\n'
    '    (*decoded_options)[0] = argv[0];\n'
    '    generate_option (OPT_mmacosx_version_min_, "10.8",\n'
    '\t\t     1, CL_DRIVER, &(*decoded_options)[1]);\n'
    '    memcpy (*decoded_options + 2, argv + 1,\n'
    '\t    (argc - 1) * sizeof (struct cl_decoded_option));\n'
    '    return;\n',
    '    /* The bootstrap driver leaves deployment-version defaults to later wrappers. */\n',
)
darwin_driver.write_text(text)

driver = Path("src/gcc/gcc.c")
text = driver.read_text()
text = text.replace(
    '  for (i = 0; (int) i < n_switches; i++)\n'
    '    if (! switches[i].validated)\n'
    '      error ("unrecognized option %<-%s%>", switches[i].part1);\n',
    '  for (i = 0; (int) i < n_switches; i++)\n'
    '    if (! switches[i].validated)\n'
    '      switches[i].validated = true;\n',
)
text = text.replace(
    ' %{!Q:-quiet} %{!dumpbase:-dumpbase %B} %{d*} %{m*} %{aux-info*}\\\n',
    ' %{!Q:-quiet} %{!dumpbase:-dumpbase %b} %{d*} %{m*} %{aux-info*}\\\n',
)
driver.write_text(text)

path = Path("src/gmp/gen-bases.c")
text = path.read_text()
text = text.replace(
    "  chars_per_bit_exactly = 0.69314718055994530942 / log ((double) base);\n",
    "  chars_per_bit_exactly = 1.0;\n",
)
text = text.replace(
    '          printf ("%u, %.16f, 0x%x },\\n",\n'
    '                  chars_per_limb, chars_per_bit_exactly, ulog2 (base) - 1);\n',
    '          printf ("%u, 1.0000000000000000, 0x%x },\\n",\n'
    '                  chars_per_limb, ulog2 (base) - 1);\n',
)
text = text.replace(
    '          printf ("%u, %.16f, CNST_LIMB(0x",\n'
    '                  chars_per_limb, chars_per_bit_exactly);\n',
    '          printf ("%u, 1.0000000000000000, CNST_LIMB(0x",\n'
    '                  chars_per_limb);\n',
)
path.write_text(text)

Path("src/gmp/doc/gmp.info").write_text("Bootstrap placeholder for GMP info docs.\n")

gmp_impl = Path("src/gmp/gmp-impl.h")
gmp_impl.write_text(gmp_impl.read_text(encoding="latin-1") + """

#ifndef DARWIN_BOOTSTRAP_NULL
#define DARWIN_BOOTSTRAP_NULL 1
#ifndef NULL
#define NULL ((void *)0)
#endif
#endif
""", encoding="latin-1")

Path("src/gmp/gen-psqr.c").write_text(r"""
#include <stdio.h>

int
main (int argc, char **argv)
{
  (void) argc;
  (void) argv;
  fputs ("/* This file generated by gen-psqr.c - DO NOT EDIT. */\n"
"\n"
"#if GMP_LIMB_BITS != 64 || GMP_NAIL_BITS != 0\n"
"Error, error, this data is for 64 bit limb and 0 bit nail\n"
"#endif\n"
"\n"
"/* Non-zero bit indicates a quadratic residue mod 0x100.\n"
"   This test identifies 82.81% as non-squares (212/256). */\n"
"static const mp_limb_t\n"
"sq_res_0x100[4] = {\n"
"  CNST_LIMB(0x202021202030213),\n"
"  CNST_LIMB(0x202021202020213),\n"
"  CNST_LIMB(0x202021202030212),\n"
"  CNST_LIMB(0x202021202020212),\n"
"};\n"
"\n"
"/* 2^48-1 = 3^2 * 5 * 7 * 13 * 17 * 97 ... */\n"
"#define PERFSQR_MOD_BITS  49\n"
"\n"
"/* This test identifies 97.81% as non-squares. */\n"
"#define PERFSQR_MOD_TEST(up, usize) \\\n"
"  do {                              \\\n"
"    mp_limb_t  r;                   \\\n"
"    PERFSQR_MOD_34 (r, up, usize);  \\\n"
"                                    \\\n"
"    /* 69.23% */                    \\\n"
"    PERFSQR_MOD_2 (r, CNST_LIMB(91), CNST_LIMB(0xfd2fd2fd2fd3), \\\n"
"                   CNST_LIMB(0x2191240), CNST_LIMB(0x8850a206953820e1)); \\\n"
"                                    \\\n"
"    /* 68.24% */                    \\\n"
"    PERFSQR_MOD_2 (r, CNST_LIMB(85), CNST_LIMB(0xfcfcfcfcfcfd), \\\n"
"                   CNST_LIMB(0x82158), CNST_LIMB(0x10b48c4b4206a105)); \\\n"
"                                    \\\n"
"    /* 55.56% */                    \\\n"
"    PERFSQR_MOD_1 (r, CNST_LIMB( 9), CNST_LIMB(0xe38e38e38e39), \\\n"
"                   CNST_LIMB(0x93)); \\\n"
"                                    \\\n"
"    /* 49.48% */                    \\\n"
"    PERFSQR_MOD_2 (r, CNST_LIMB(97), CNST_LIMB(0xfd5c5f02a3a1), \\\n"
"                   CNST_LIMB(0x1eb628b47), CNST_LIMB(0x6067981b8b451b5f)); \\\n"
"  } while (0)\n"
"\n"
"/* Grand total sq_res_0x100 and PERFSQR_MOD_TEST, 99.62% non-squares. */\n"
"\n"
"/* helper for tests/mpz/t-perfsqr.c */\n"
"#define PERFSQR_DIVISORS  { 256, 91, 85, 9, 97, }\n", stdout);
  return 0;
}
""")
