#!/usr/bin/env bash
## Prepare GCC 4.6 source for the Darwin bootstrap build.  Performs a fixed
## set of text edits that compensate for differences between modern macOS and
## the old x86_64 ABI that the bootstrap targets, plus a few small fixes to
## ship GMP / its generators under an early Mach-O libc.
set -eu

## Deterministic GCC 4.6 source edits (CC1_SPEC version selector, driver
## deployment-version block, %B->%b spec, gen-bases libm removal, incpath
## name-based dedup): a committed patch applied by the caller-provided
## patch tool (shell track: chain-built boot-patch; Nix track:
## chain-built gnupatch).  No host perl edits source.  Regen: re-run
## the historical perl (git history) against gcc46-darwin-bootstrap-
## source and diff.
"${GNUPATCH:?}" -p1 -d src < "${PREPARE_SOURCE_PATCH:?}"





## 5) gmp/doc/gmp.info — stub out doc to avoid texinfo dependency.
printf 'Bootstrap placeholder for GMP info docs.\n' > src/gmp/doc/gmp.info

## 6) gmp-impl.h — append NULL macro so early libc-less builds can include it.
cat >> src/gmp/gmp-impl.h <<'EOF'


#ifndef DARWIN_BOOTSTRAP_NULL
#define DARWIN_BOOTSTRAP_NULL 1
#ifndef NULL
#define NULL ((void *)0)
#endif
#endif
EOF

## 7) gmp/gen-psqr.c — replace with a stub that emits a hardcoded table; the
## real generator needs floating-point and large-prime arithmetic that early
## tinycc can't yet compile cleanly.
cat > src/gmp/gen-psqr.c <<'PSQR'

#include <stdio.h>

int
main (int argc, char **argv)
{
  (void) argc;
  (void) argv;
  fputs ("/* This file generated by gen-psqr.c - DO NOT EDIT. */\n"
"\n"
"#if GMP_LIMB_BITS != 64 || GMP_NAIL_BITS != 0\n"
"Error, error, this data is for 64 bit limb and 0 bit nail\n"
"#endif\n"
"\n"
"/* Non-zero bit indicates a quadratic residue mod 0x100.\n"
"   This test identifies 82.81% as non-squares (212/256). */\n"
"static const mp_limb_t\n"
"sq_res_0x100[4] = {\n"
"  CNST_LIMB(0x202021202030213),\n"
"  CNST_LIMB(0x202021202020213),\n"
"  CNST_LIMB(0x202021202030212),\n"
"  CNST_LIMB(0x202021202020212),\n"
"};\n"
"\n"
"/* 2^48-1 = 3^2 * 5 * 7 * 13 * 17 * 97 ... */\n"
"#define PERFSQR_MOD_BITS  49\n"
"\n"
"/* This test identifies 97.81% as non-squares. */\n"
"#define PERFSQR_MOD_TEST(up, usize) \\\n"
"  do {                              \\\n"
"    mp_limb_t  r;                   \\\n"
"    PERFSQR_MOD_34 (r, up, usize);  \\\n"
"                                    \\\n"
"    /* 69.23% */                    \\\n"
"    PERFSQR_MOD_2 (r, CNST_LIMB(91), CNST_LIMB(0xfd2fd2fd2fd3), \\\n"
"                   CNST_LIMB(0x2191240), CNST_LIMB(0x8850a206953820e1)); \\\n"
"                                    \\\n"
"    /* 68.24% */                    \\\n"
"    PERFSQR_MOD_2 (r, CNST_LIMB(85), CNST_LIMB(0xfcfcfcfcfcfd), \\\n"
"                   CNST_LIMB(0x82158), CNST_LIMB(0x10b48c4b4206a105)); \\\n"
"                                    \\\n"
"    /* 55.56% */                    \\\n"
"    PERFSQR_MOD_1 (r, CNST_LIMB( 9), CNST_LIMB(0xe38e38e38e39), \\\n"
"                   CNST_LIMB(0x93)); \\\n"
"                                    \\\n"
"    /* 49.48% */                    \\\n"
"    PERFSQR_MOD_2 (r, CNST_LIMB(97), CNST_LIMB(0xfd5c5f02a3a1), \\\n"
"                   CNST_LIMB(0x1eb628b47), CNST_LIMB(0x6067981b8b451b5f)); \\\n"
"  } while (0)\n"
"\n"
"/* Grand total sq_res_0x100 and PERFSQR_MOD_TEST, 99.62% non-squares. */\n"
"\n"
"/* helper for tests/mpz/t-perfsqr.c */\n"
"#define PERFSQR_DIVISORS  { 256, 91, 85, 9, 97, }\n", stdout);
  return 0;
}
PSQR
