#!/bin/sh
## 35-tinycc-self-link — link the self-compiled tcc into a runnable
## tcc-self binary with its own libc.
##
## Self-hosting property established: the compiler compiled by
## itself runs — tcc-self is tinycc code generated by tinycc
## (generation 1 of the boot cycle).  It also swaps libcs: the
## step-27 tcc runs on the mescc-built mes libc; tcc-self links
## against tinycc-sysv-libc.c compiled by tcc itself, plus the
## hand-written Darwin syscall M1, so no mescc-generated code remains
## in the compiler binary.
##
## Runs:     tcc (built in step 27), elf64-to-m1 (step 30), M1 (step
##           12), hex2 (step 13), hex2-data-relocs (step 34); host
##           awk — trust boundary — M1 code/data splits; Apple
##           /usr/bin cp/dd/chmod/install/grep for orchestration.
## Inputs:   sources/bootstrap-c/tinycc-sysv-libc.c (libc for
##           tcc-generated SysV-ABI code) and
##           tinycc-sysv-syscalls-amd64-darwin.M1 (hand-written
##           Darwin syscall stubs),
##           sources/tinycc-fixtures/self-link-crt1-tcc-sysv.M1,
##           target/share/tinycc-self-m1/tcc-from-elf.M1 (step 32),
##           sources/stage0-posix/M2libc/amd64/MACHO-amd64-lowdata.hex2.
## Outputs:  target/bin/tcc-self.
## Verifies: smoke run — `tcc-self -version` prints the pinned
##           version string with empty stderr.
## Trust:    host awk for the M1 code/data splits.
set -eu

work="$TARGET/work/tinycc-self-link"
rm -rf "$work"
mkdir -p "$work"
cd "$work"

tcc -c "$SOURCES/bootstrap-c/tinycc-sysv-libc.c" -o tinycc-sysv-libc.o \
    > tinycc-sysv-libc.stdout 2> tinycc-sysv-libc.stderr

elf64-to-m1 --prefix tinycc_sysv_libc_ \
    tinycc-sysv-libc.o \
    tinycc-sysv-libc.M1

cp "$SOURCES/tinycc-fixtures/self-link-crt1-tcc-sysv.M1" crt1-tcc-sysv.M1

emit_code() {
    awk '
      /^:ELF_data$/ { data = 1; next }
      /^:HEX2_data$/ { next }
      data != 1 { print }
    ' "$1"
}
emit_data() {
    awk '
      /^:ELF_data$/ { data = 1; next }
      /^:HEX2_data$/ { next }
      data == 1 { print }
    ' "$1"
}

## Combine: crt1 entry stub, hand-written syscall stubs, then the
## code sections of the converted compiler + libc objects, one
## section boundary, and their data sections.
{
    cat crt1-tcc-sysv.M1
    cat "$SOURCES/bootstrap-c/tinycc-sysv-syscalls-amd64-darwin.M1"
    emit_code "$TARGET/share/tinycc-self-m1/tcc-from-elf.M1"
    emit_code tinycc-sysv-libc.M1
    echo ':ELF_data'
    echo ':HEX2_data'
    emit_data "$TARGET/share/tinycc-self-m1/tcc-from-elf.M1"
    emit_data tinycc-sysv-libc.M1
} > tcc-self-combined.M1

M1 --architecture amd64 --little-endian \
    -f tcc-self-combined.M1 \
    -o tcc-self.hex2

hex2 --architecture amd64 --little-endian \
    --base-address 0x1000000 \
    -f "$SOURCES/stage0-posix/M2libc/amd64/MACHO-amd64-lowdata.hex2" \
    -f tcc-self.hex2 \
    -o tcc-self

## First use of the source-driven patcher (step 34): every % and &
## reference site recorded in tcc-self.hex2 is rewritten for the
## split __TEXT/__DATA layout.
hex2-data-relocs patch tcc-self.hex2 tcc-self

## Pad to 0x2800000 (40 MiB), the fixed template's declared extent.
dd if=/dev/zero of=tcc-self bs=1 count=1 seek=41943039 conv=notrunc 2>/dev/null || true
chmod +x tcc-self
install tcc-self "$TARGET/bin/tcc-self"

## Smoke test
"$TARGET/bin/tcc-self" -version > tcc-self-version.stdout 2> tcc-self-version.stderr
grep -q '0.9.28-darwin-bootstrap' tcc-self-version.stdout
test ! -s tcc-self-version.stderr
